# Generated by Django 2.0.7 on 2018-07-22 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text', models.CharField(max_length=200)),
                ('size_text', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('COFFEE', 'Coffee'), ('TEA', 'Tea')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Type'),
        ),
    ]
